
#define VK_NO_PROTOTYPES
#include "vulkan/vulkan.h"

#define VK_EXPORTED_FUNCTION( fun ) PFN_##fun fun;
#define VK_GLOBAL_LEVEL_FUNCTION( fun) PFN_##fun fun;
#define VK_INSTANCE_LEVEL_FUNCTION( fun ) PFN_##fun fun;
#define VK_DEVICE_LEVEL_FUNCTION( fun ) PFN_##fun fun;

#define USE_KHR_SWAPCHAIN_EXTENSION
#define USE_KHR_DISPLAY_EXTENSION
#define USE_KHR_SURFACE_EXTENSION
#define USE_KHR_WIN32_SURFACE_EXTENSION
#define USE_EXT_DEBUG_REPORT_EXTENSION
#define USE_KHR_DISPLAY_SWAPCHAIN_EXTENSION

#include "VulkanFunctions.inl"

#undef USE_KHR_SWAPCHAIN_EXTENSION
#undef USE_KHR_DISPLAY_EXTENSION
#undef USE_KHR_SURFACE_EXTENSION
#undef USE_KHR_WIN32_SURFACE_EXTENSION
#undef USE_EXT_DEBUG_REPORT_EXTENSION
#undef USE_KHR_DISPLAY_SWAPCHAIN_EXTENSION

HMODULE VulkanLibrary;
